// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLMZSAPbYiLQzD1Y_XYV001rQ27jdG5Sc',
    appId: '1:1074410806955:web:029d7ef3860cbb1c7561ee',
    messagingSenderId: '1074410806955',
    projectId: 'jarnama-exzemple',
    authDomain: 'jarnama-exzemple.firebaseapp.com',
    storageBucket: 'jarnama-exzemple.appspot.com',
    measurementId: 'G-FRC1VE0V0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWzrkdIAe8oJovSktUqAuQB2Kr9eFAuDU',
    appId: '1:1074410806955:android:a7f4e0e6942560847561ee',
    messagingSenderId: '1074410806955',
    projectId: 'jarnama-exzemple',
    storageBucket: 'jarnama-exzemple.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQCwd5E5UKlllCUzXAvOa4XnF0DwHsTec',
    appId: '1:1074410806955:ios:d5d5cd2dc9bbb8ec7561ee',
    messagingSenderId: '1074410806955',
    projectId: 'jarnama-exzemple',
    storageBucket: 'jarnama-exzemple.appspot.com',
    iosClientId: '1074410806955-vjcuolcbel4i37cmlk0st1509l4ra8e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaExzemple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQCwd5E5UKlllCUzXAvOa4XnF0DwHsTec',
    appId: '1:1074410806955:ios:d5d5cd2dc9bbb8ec7561ee',
    messagingSenderId: '1074410806955',
    projectId: 'jarnama-exzemple',
    storageBucket: 'jarnama-exzemple.appspot.com',
    iosClientId: '1074410806955-vjcuolcbel4i37cmlk0st1509l4ra8e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaExzemple',
  );
}
